language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "pip install mock"
  - "pip install coveralls"
script:
  nosetests --with-coverage --cover-package luigi_td
after_success:
  coveralls
deploy:
  provider: pypi
  user: k24d
  password:
    secure: ZvXpIIOBt70v0ihIMc+6308VGl3tj+o4c46Pin/Fv8D8TzWI2cvKuhA1yhSA1nWRCTa0njOrDko8jrWBd3nVqnurGzYqYSCXsgRF+4oDxfErIpBUh+ty5SZzUS0lD4wOxx5llZP3QLtZr9mwtbzrTaK1ZcAT+UGm8w4IgCpr8OoYhSnyKQm3snakeUChVW60y40LN/vNrCE4ik366f41e0ir1VFN1R1ScUjKhzuqpICcCow/2cjnUso9Bb5yqfT67+bYkuGd3KyOADF8/h9sReHhMTyD+lT8+Qphx7Bj5WdRC7dsue7HJ3ehksQmwKzwMlwLPlqoK0jkcIjJLOkcwuFvRr9JHJeZ27DZjoNHG2/zn7TWOpvlJBxFomnaEX9cKRmFCWyQy3we1h7S/5ESHt/6+0YZ2xm6VsexJ4+4o2R1y7BD+u+CfYCBzCqj9LfYEPLsHZwWXLwAk/rMVq5O7jfLG1gMe9xkMvhO+/1GZTWnGHKD57FKRb8hpznrzGRaDtKtLSWjg+Ns0DUZe/aroR5H4PW59gLfbQAtq6GmYXAjpaXvrsOG2y0YaV7i3GiLNwV0R5rkUBaunqQw1KX/SH51wWxLrkeRSHPZrgbYbMWXh4K5SRrF2Flo2dHAeY3+oy+l8+3Jj2TFfA2pj/RG3AqfnFet6Ufm7LcF/SN4u6M=
  on:
    tags: true
    repo: treasure-data/luigi-td
